#!/bin/bash

echo -n "Sisesta suvaline täisarv: "
read  arv
arv1=$arv
summa=0
while [ $arv -ne 0 ]

do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$((arv / 10))
done
echo "Arvu $arv1 numbrite summa on $summa"
